In [8]:
print("hello ddd")

hello ddd


In [24]:
import numpy
#print(help(numpy.genfromtxt))
vertor = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45],[25,25,25]])
print(type(vertor))
print(matrix.shape)
print(matrix)
print(matrix.dtype)
matrix[0,1]
matrix[:,1]
matrix[0:2,:]
equal_to_ten = matrix == 25
matrix[equal_to_ten]

<class 'numpy.ndarray'>
(4, 3)
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [25 25 25]]
int32


array([25, 25, 25, 25])

In [7]:
import numpy
print(help(numpy.sum))

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In t

In [10]:
import numpy  as np
print(np.arange(15))
a = np.arange(15).reshape(3,5)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2


In [15]:
import numpy  as np
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
import numpy  as np
np.random.rand(2,3)
from numpy  import pi
np.linspace( 0, 2*pi, 100)


a = np.array([[20,30,40,50],[20,30,40,50]])
b = np.arange(8).reshape(2,4)
c = np.arange(8).reshape(4,2)
print(a)
print(b)
print(a-b)
print(a*b)
print(a**b)
print(a-1)
print(b**2)
print(a.dot(c))

[[20 30 40 50]
 [20 30 40 50]]
[[0 1 2 3]
 [4 5 6 7]]
[[20 29 38 47]
 [16 25 34 43]]
[[  0  30  80 150]
 [ 80 150 240 350]]
[[         1         30       1600     125000]
 [    160000   24300000 -198967296 -434047872]]
[[19 29 39 49]
 [19 29 39 49]]
[[ 0  1  4  9]
 [16 25 36 49]]
[[520 660]
 [520 660]]


In [37]:
import numpy as np
d = np.arange(3)
print(d)
print(np.exp(d))
print(np.sqrt(d))
a = np.arange(15).reshape(3,5)
print(a)

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [44]:
import numpy as np
a = np.floor(10 * np.random.rand(2,2))
b = np.floor(10 * np.random.rand(2,2))
print(a)
print(b)
A = np.floor(10 * np.random.rand(2,12))
B= A.T
print(A)
print(B)
print(np.hsplit(A,3))
print(np.vsplit(B,3))

[[4. 3.]
 [7. 7.]]
[[9. 2.]
 [5. 7.]]
[[3. 8. 9. 7. 7. 5. 0. 0. 8. 1. 1. 1.]
 [0. 9. 9. 4. 4. 1. 2. 5. 6. 5. 2. 7.]]
[[3. 0.]
 [8. 9.]
 [9. 9.]
 [7. 4.]
 [7. 4.]
 [5. 1.]
 [0. 2.]
 [0. 5.]
 [8. 6.]
 [1. 5.]
 [1. 2.]
 [1. 7.]]
[array([[3., 8., 9., 7.],
       [0., 9., 9., 4.]]), array([[7., 5., 0., 0.],
       [4., 1., 2., 5.]]), array([[8., 1., 1., 1.],
       [6., 5., 2., 7.]])]
[array([[3., 0.],
       [8., 9.],
       [9., 9.],
       [7., 4.]]), array([[7., 4.],
       [5., 1.],
       [0., 2.],
       [0., 5.]]), array([[8., 6.],
       [1., 5.],
       [1., 2.],
       [1., 7.]])]


In [51]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
index = data.argmax(axis = 0)
index2 = data.argmax(axis = 1)
print(data)
print(index)
print(index2)
data_max = data[index, np.arange(data.shape[1])]
print(data_max)
data_max2 = data[np.arange(data.shape[0]), index2]
print(data_max2)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[2 3 0 2 3]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
[0.90929743 0.6569866  0.98935825 0.99060736 0.14987721]


In [15]:
import numpy as np
a = np.array([[4,3,5],[1,2,1]])
print(a)
b = np.sort(a, axis = 0)
print(b)
#a.sort(axis =1)
print(a)

a= np.array([1,2,3,4,5])
j = np.argsort(a)
print(j)
#print(a[j])
print(a[j])

[[4 3 5]
 [1 2 1]]
[[1 2 1]
 [4 3 5]]
[[4 3 5]
 [1 2 1]]
[0 1 2 3 4]
[1 2 3 4 5]
